#!/bin/sh /etc/rc.common

START=40
STOP=83
USE_PROCD=1

SERVICE=/usr/sbin/tsmsmscomm
SERVICE_PID_FILE=/var/run/tsmsmscomm.pid
SERVICE_USE_PID=1

  . /lib/functions.sh
INCLUDE_ONLY=1 . $SERVICE

start_service() {
    procd_open_instance 'tsmsmscomm'

    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param command $SERVICE
    procd_set_param pidfile $SERVICE_PID_FILE
    procd_close_instance

}

service_triggers()
{
    procd_add_reload_trigger "tsmsmscomm"
}

stop_service() {

    kill -9 `ps | grep '/usr/lib/lua/tsmsmscomm/app.lua' | grep -v grep | awk '{print $1}'`
    
    [ -x $SERVICE_PID_FILE ] && {
        rm $SERVICE_PID_FILE
    }
}
